### ISSUE TITLE
Mock-up Julius in AL nabouwen

### ISSUE THREAD

**Issue by naudloomans** [Zenmo/Local4Local#2]

**Comment by naudloomans** [comment]
- [ ] input scherm
- [ ] output jaartotalen energieverbruik, energieopwek, perc. gelijktijdigheid, etc.
- [ ] ouput grafiek issue 4

**Comment by Erikvv** [comment]
Kan deze mockup nergens meer vinden. Zal nieuwe issues maken voor hoe we het nu doen.
