### ISSUE TITLE
Input kosten

### ISSUE THREAD

**Issue by Erikvv** [Zenmo/Local4Local#26]
Bij een opwekasset aangeven

- kosten per kWh
    - Toelichting: Dit gebruik je op basis van ervaring/expert judgement. De voorgaande 4 velden laat je dan leeg.
    - Niet voor batterijen
- aanschaf [€]
- rente [%]
- afschrijvingsperiode [jaar]
- onderhoudskosten [€/jaar]

Deze kosten rekenen we aan het eind van de jaarsimulatie om tot een kostprijs van de opgewekte energie in [ct/kWh].

Voor het gehele scenario

- Leverancierskosten, waaronder onbalanskosten, platform kosten (zaken als ENTRNCE), personeelskosten, etc. Dit wil je waarschijnlijk platslaan tot één opslag op het stroomtarief, we noemen dit vaak een 'bufferprijs [ct/kWh].

Tasks:

- [ ] DTO object for costs in module "common", add it to each asset
- [ ] Implement forms
- [ ] Add field for organizational overhead costs in DTO
- [ ] Add form for organizational overhead costs

**Comment by macano** [comment]
defaultValue, min or max value for cost? defaultValue=0 min=0?

**Comment by Erikvv** [comment]
> defaultValue, min or max value for cost? defaultValue=0 min=0?

It feels natural to me to have the default be empty. Also the user can start typing without removing the 0. 

(But 0 is easier in the calculation. Maybe we can have it be 0 in the data class)

**Comment by Erikvv** [comment]
Done
