### ISSUE TITLE
Webpagina aanmaken waarbinnen we Iframe en plots kunnen laten zien

### ISSUE THREAD

**Issue by naudloomans** [Zenmo/Local4Local#6]

**Comment by naudloomans** [comment]
Basic webpagina met logo, tekst en iframe

**Comment by Erikvv** [comment]
Site staat live op https://white-pond-042fb1903.4.azurestaticapps.net/

HTML en deploy code staat in deze repo.

Ik ga op zoek naar een logo.

**Comment by Erikvv** [comment]
Done
