### ISSUE TITLE
Onbalans-kostenpost

### ISSUE THREAD

**Issue by Erikvv** [Zenmo/Local4Local#66]
Naast bufferprijs zou een aparte onbalanspost (kostenvoor verschil voorspelling-werkelijkheid) mooi zijn om te benadrukken dat dit een significante post is.

Zou kunnen worden uitgedrukt in percentage van de levering, bv 8%.

**Comment by Erikvv** [comment]
Done

**Comment by Erikvv** [comment]
Moet nog aan simulatiemodel worden toegevoegd.

**Comment by GillisHommen** [comment]
Is deze op te vragen vanuit de anylogic client? (met een nieuwe versie?)

**Comment by Erikvv** [comment]
Ja ik heb een nieuwe jar gepusht naar https://github.com/Zenmo/Local4Local/blob/main/webtool/gradle/client/build/libs/local4local-client.jar

**Comment by GillisHommen** [comment]
Onbalanskosten worden meegenomen in f_getFinances in EnergyCoopL4L
