### ISSUE TITLE
Card kunnen bewerken

### ISSUE THREAD

**Issue by Erikvv** [Zenmo/Local4Local#69]
Je kunt nu toevoegen en verwijderen maar niet bewerken. Vooral handig voor huishoudens.

**Comment by GillisHommen** [comment]
@Erikvv, denk je dat je hier nog aan toe komt deze week?

**Comment by GillisHommen** [comment]
What is the status of this issue? Has it been applied to all cards or only households and leverancierskosten?

**Comment by Erikvv** [comment]
Done
