### ISSUE TITLE
Toevoegen veld 'SDE subsidietarief [ct/kWh]' aan opwek assets als windmolens, zonneparken en stortgasmotor.

### ISSUE THREAD

**Issue by GillisHommen** [Zenmo/Local4Local#75]

**Comment by GillisHommen** [comment]
I think this field is not yet reachable from the anylogic client. (there is no getter for SDEsubsidy) 
@macano, could you add this to the local4local-client.jar?

**Comment by Erikvv** [comment]
If it isn't there (AssetCost.getSdeSubsidy_eurpkWH()) all it should need is a recompile using `docker compose run --rm gradle-client-shadowjar`

**Comment by GillisHommen** [comment]
@macano did a recompile and now the getter is there!
