### ISSUE TITLE
Updating terms in configuration-page of web-app

### ISSUE THREAD

**Issue by GillisHommen** [Zenmo/Local4Local#79]
In the configuration-page of the Cooperatie Configator, I'd like to update the following terms:

- [ ] Bufferprijs [€/kWh]-> Leveranciersopslag  [€/kWh]
- [ ] For huishoudens; “Jaarlijks gemiddeld verbruik” -> “Jaarlijks huishoudelijk verbruik”
- [ ] For huishoudens, hide field “Percentage met thuisbatterij”.
- [ ] For opwek-assets, “SDE subsidietarief [ct/kWh]” -> “SDE subsidietarief [€/kWh]”

**Comment by macano** [comment]
changes in https://github.com/Zenmo/Local4Local/pull/87

**Comment by macano** [comment]
https://github.com/Zenmo/Local4Local/pull/87
